[package]
name = "WuWaModFixUltraPerformanceGraphic"
version = "0.1.0"
edition = "2024"

[dependencies]
fs = "0.0.5"
regex = "1.11.1"
reqwest = { version = "0.12", features = ["blocking"] }
rfd = "0.15.2"
